### ISSUE TITLE
Update CSS frameworks that will be used for the project - add tags

### ISSUE THREAD

**Issue by brundabharadwaj** [brundabharadwaj/hotel-booking-application-portal#7]
Let's update these details of the project for clarity

**Comment by adarsh-dayanand** [comment]
1. tailwindcss
2. material design & icons
3. ant design

**Comment by brundabharadwaj** [comment]
> 1. tailwindcss
> 2. material design & icons
> 3. ant design

![image](https://github.com/brundabharadwaj/hotel-booking-application-portal/assets/49773125/9467d5b0-3539-47dc-95bf-cf8bbf6500e5)
We can tag here  😃

**Comment by adarsh-dayanand** [comment]
No access 🫤

**Comment by brundabharadwaj** [comment]
Sorry for that , but I have updated the details and this can be closed :)
